version: "3.9"

services:
  db:
    image: mysql:8
    container_name: praxis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: praxis
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - praxis-net

  backend:
    build: ./booking-appointment-svc
    container_name: praxis-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/praxis
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    networks:
      - praxis-net

  frontend:
    build: ./booking-appointment-application
    container_name: praxis-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - praxis-net

networks:
  praxis-net:
    driver: bridge
